# Generated by Django 4.2.16 on 2024-10-30 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_author_options_borrow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrow',
            options={'permissions': [('can_mark_returned', 'Can mark books as returned')]},
        ),
    ]
